const postsListings = [
  {
    id: "1",
    user_id: "user1",
    username: "john_doe",
    title: "First Post",
    description: "This is the first post",
    created_at: "2024-03-25",
    edited_at: "2024-03-25",
    deleted_at: "2024-03-25",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image1.jpg",
        caption: "Image 1",
        link: "https://example.com/image1.jpg",
      },
    ],
    videos: [
      {
        path: "video1.mp4",
        caption: "Video 1",
        link: "https://example.com/video1.mp4",
      },
    ],
    poll: {
      options: ["Option 1", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community1",
    "community-name": "Community 1",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator1",
      approved_date: "2024-03-25",
      removed_by: "moderator2",
      removed_date: "2024-03-25",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
  {
    id: "2",
    user_id: "user2",
    username: "jane_smith",
    title: "Second Post",
    description: "This is the second post",
    created_at: "2024-03-26",
    edited_at: "2024-03-26",
    deleted_at: "2024-03-26",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image2.jpg",
        caption: "Image 2",
        link: "https://example.com/image2.jpg",
      },
    ],
    videos: [
      {
        path: "video2.mp4",
        caption: "Video 2",
        link: "https://example.com/video2.mp4",
      },
    ],
    poll: {
      options: ["Option 1", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community2",
    "community-name": "Community 2",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator1",
      approved_date: "2024-03-26",
      removed_by: "moderator2",
      removed_date: "2024-03-26",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
  {
    id: "3",
    user_id: "user3",
    username: "joe_bloggs",
    title: "Third Post",
    description: "This is the third post",
    created_at: "2024-03-27",
    edited_at: "2024-03-27",
    deleted_at: "2024-03-27",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image3.jpg",
        caption: "Image 3",
        link: "https://example.com/image3.jpg",
      },
    ],
    videos: [
      {
        path: "video3.mp4",
        caption: "Video 3",
        link: "https://example.com/video3.mp4",
      },
    ],
    poll: {
      options: ["Option 1", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community3",
    "community-name": "Community 3",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator1",
      approved_date: "2024-03-27",
      removed_by: "moderator2",
      removed_date: "2024-03-27",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
  {
    id: "4",
    user_id: "user4",
    username: "john_doe",
    title: "First Post",
    description: "This is the first post",
    created_at: "2024-03-25",
    edited_at: "2024-03-25",
    deleted_at: "2024-03-25",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image4.jpg",
        caption: "Image 4",
        link: "https://example.com/image4.jpg",
      },
    ],
    videos: [
      {
        path: "video4.mp4",
        caption: "Video 4",
        link: "https://example.com/video4.mp4",
      },
    ],
    poll: {
      options: ["Option 4", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community4",
    "community-name": "Community 4",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator4",
      approved_date: "2024-03-25",
      removed_by: "moderator2",
      removed_date: "2024-03-25",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
  {
    id: "5",
    user_id: "user5",
    username: "joe_bloggs",
    title: "Third Post",
    description: "This is the third post",
    created_at: "2024-05-27",
    edited_at: "2024-05-27",
    deleted_at: "2024-05-27",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image5.jpg",
        caption: "Image 5",
        link: "https://example.com/image5.jpg",
      },
    ],
    videos: [
      {
        path: "video5.mp4",
        caption: "Video 5",
        link: "https://example.com/video5.mp4",
      },
    ],
    poll: {
      options: ["Option 1", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community3",
    "community-name": "Community 3",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator1",
      approved_date: "2024-03-27",
      removed_by: "moderator2",
      removed_date: "2024-03-27",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
  {
    id: "6",
    user_id: "user6",
    username: "jane_smith",
    title: "Second Post",
    description: "This is the second post",
    created_at: "2024-03-26",
    edited_at: "2024-03-26",
    deleted_at: "2024-03-26",
    type: "image_and_videos",
    link_url: "https://example.com",
    images: [
      {
        path: "image2.jpg",
        caption: "Image 2",
        link: "https://example.com/image2.jpg",
      },
    ],
    videos: [
      {
        path: "video2.mp4",
        caption: "Video 2",
        link: "https://example.com/video2.mp4",
      },
    ],
    poll: {
      options: ["Option 1", "Option 2", "Option 3"],
      votes: [0, 0, 0],
    },
    community_id: "community2",
    "community-name": "Community 2",
    comments_count: 0,
    views_count: 0,
    shares_count: 0,
    upvotes_count: 0,
    downvotes_count: 0,
    oc_flag: true,
    spoiler_flag: true,
    nsfw_flag: true,
    locked_flag: true,
    allowreplies_flag: true,
    set_suggested_sort: "None (Recommended)",
    moderator_details: {
      approved_by: "moderator1",
      approved_date: "2024-03-26",
      removed_by: "moderator2",
      removed_date: "2024-03-26",
      spammed_by: "moderator3",
      spammed_type: "spam",
    },
    user_details: {
      total_views: 0,
      upvote_rate: 0,
      total_shares: 0,
    },
  },
];

export default postsListings;
