name: APPROVE

on: pull_request

permissions:
    pull-requests: write

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Approve Pull Request
        run: |
          curl --request POST \
          --url "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "content-type: application/json" \
          --data '{"event": "APPROVE"}'
