# CD FRONTEND

name: CD FE

on:
  push:
    branches:
      - master
jobs:
  build_push_docker:
    name: Build Frontend For Prod files and push to docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Frontend For Prod files
        run: |
          docker build -t aoudaa/dkr-frontend:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Frontend image

        run: |
          docker push aoudaa/dkr-frontend:latest

  deploy:
    name: Deploy Frontend For Prod files
    runs-on: ubuntu-latest
    needs: build_push_docker

    steps:
      - name: ssh into vm and run the script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/aoudaa/docker
            sh deployFE.sh
